### PR TITLE
Relax time dependency

### PR DESCRIPTION
**Pull request by PierreR**

### CODE REVIEW

**Comment by PierreR** [comment]
I have just tested the master branch on `os x` and it works fine.

My understanding is that the issue with the tests are related to the `tmp` in the test framework so maybe we could release this and  by-pass the test on os x in travis for now ?

**Comment by bartavelle** [comment]
Yup, except I am not sure how to do that in the travis script!

**Comment by bartavelle** [comment]
I think I did it!

**Comment by bartavelle** [comment]
0.3.0 is up

**Comment by PierreR** [comment]
Thanks !

I have got lot's of 
```
/home/vagrant/projects/bric/cicd/puppet/cicd/hieradata/prod/cicd/: can't watch what isn't there!: does not exist
````
These directories don't exist indeed; there are part of the hierarchy defined in hiera.yaml. Maybe we should check the existence of the directory before trying to cache it ? If so I don't really know if this check should be here or in `Hiera.Server` module in language-puppet.

**Comment by bartavelle** [comment]
It should happen in `Hiera.Server` IMO.

**Pull request merged**
